services:
  observer:
    build:
      context: .
      dockerfile: "build/dev/Dockerfile"
    container_name: observer
    user: "${DOCKER_USER}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      APP_ENV: "dev"
      APP_DEBUG: "1"
      APP_KEY: "base64:cKIAHpfPQfioXrZlYegBXiqqc508cK91eF8wnTR7stI="
      XDG_CONFIG_HOME: "/application/.config"
      API_AUTH_TOKEN: "4a63bb7c-1e14-4cf0-ba31-ddcddf79b277"
      RABBITMQ_IS_SECURE: false
    volumes:
      - ./src:/application
      - ./docs:/docs

  observer-nginx:
    container_name: "observer-nginx"
    image: nginx:alpine
    working_dir: /application
    volumes:
      - ./src:/application
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "23331:80"
    depends_on:
      - observer

  observer-mysql:
    image: mysql:8
    command: mysqld --sql_mode=""
    container_name: "observer-mysql"
    working_dir: /application
    volumes:
      - ./src:/application:delegated
      - observer-mysql-volume:/var/lib/mysql:delegated
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "39054:3306"

volumes:
  observer-mysql-volume:
    name: observer-mysql-data

networks:
  default:
    name: "default"
    external: true
