openapi: 3.0.3
info:
  title: 'Status Monitoring'
  description: 'Status Monitoring Service'
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/policies:
    post:
      summary: ''
      operationId: postApiPolicies
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                account_id:
                  type: integer
                  description: ''
                  example: 18
                  nullable: false
                policies:
                  type: array
                  description: ''
                  example:
                    - PAGES_HEALTH_COMPREHENSIVE
                  items:
                    type: string
                    enum:
                      - PAGES_HEALTH_GENERAL
                      - PAGES_HEALTH_COMPREHENSIVE
                tenant_domain:
                  type: string
                  description: ''
                  example: eveniet
                  nullable: false
                product:
                  type: string
                  description: ''
                  example: LOCAL_LANDING_PAGES
                  nullable: false
                  enum:
                    - LOCAL_LANDING_PAGES
              required:
                - account_id
                - tenant_domain
                - product
      security: []
    delete:
      summary: ''
      operationId: deleteApiPolicies
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                account_id:
                  type: integer
                  description: ''
                  example: 4
                  nullable: false
                policies:
                  type: array
                  description: ''
                  example:
                    - PAGES_HEALTH_GENERAL
                  items:
                    type: string
                    enum:
                      - PAGES_HEALTH_GENERAL
                      - PAGES_HEALTH_COMPREHENSIVE
              required:
                - account_id
      security: []
  /api/policies/summary:
    get:
      summary: ''
      operationId: getApiPoliciesSummary
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: ''
                properties:
                  message:
                    type: string
                    example: ''
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                account_id:
                  type: integer
                  description: ''
                  example: 8
                  nullable: false
              required:
                - account_id
      security: []
  /api/incidents:
    get:
      summary: ''
      operationId: getApiIncidents
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: ''
                properties:
                  message:
                    type: string
                    example: ''
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                account_id:
                  type: integer
                  description: ''
                  example: 4
                  nullable: false
                sort:
                  type: string
                  description: ''
                  example: closed_at
                  nullable: false
                  enum:
                    - created_at
                    - closed_at
                    - severity
                direction:
                  type: string
                  description: 'This field is required when <code>sort</code> is present.'
                  example: desc
                  nullable: false
                  enum:
                    - asc
                    - desc
              required:
                - account_id
      security: []
  '/api/incidents/{incident_id}/failed-subjects':
    get:
      summary: ''
      operationId: getApiIncidentsIncident_idFailedSubjects
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: ''
                properties:
                  message:
                    type: string
                    example: ''
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                search:
                  type: string
                  description: ''
                  example: consequatur
                  nullable: false
                sort:
                  type: string
                  description: ''
                  example: meta.remote_id
                  nullable: false
                  enum:
                    - meta.remote_id
                direction:
                  type: string
                  description: 'This field is required when <code>sort</code> is present.'
                  example: asc
                  nullable: false
                  enum:
                    - asc
                    - desc
      security: []
    parameters:
      -
        in: path
        name: incident_id
        description: 'The ID of the incident.'
        example: 167
        required: true
        schema:
          type: integer
tags:
  -
    name: Endpoints
    description: ''
